# Praktikum 2

# Introduction to Machine Learning

## Pandas

In [1]:
import numpy as np
import pandas as pd

#### Series

In [ ]:
#series bisa berasal dari list, numpy array, atau dict
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

###### List

In [ ]:
pd.Series(data=my_list)

In [ ]:
pd.Series(data=my_list,index=labels)

In [ ]:
pd.Series(my_list,labels)

###### Numpy Array

In [ ]:
pd.Series(arr)

In [ ]:
pd.Series(arr,labels)

###### Dictionary

In [ ]:
pd.Series(d)

###### Data dalam sebuah Series

In [ ]:
pd.Series(data=labels)

In [ ]:
#bisa berisi fungsi juga
pd.Series([sum,print,len])

###### Menggunakan Indeks

In [ ]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])                                   

ser1

In [ ]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])                                   

ser2

In [ ]:
ser1['USA']

In [ ]:
ser1 + ser2

#### DataFrame

DataFrames adalah inti dari pandas dan terinspirasi langsung dari R. Bayangkan DataFrame sebagai kumpulan Series yang diletakkan sejajar di satu indeks.

In [36]:
from numpy.random import randn
np.random.seed(101)

In [37]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

###### Pengambilan data berdasarkan indeks

In [38]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [39]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [40]:
df.W #sintaks SQL, tidak direkomendasikan

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [41]:
type(df['W'])

pandas.core.series.Series

In [42]:
#membuat kolom baru
df['new'] = df['W'] + df['Y']

df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [43]:
#menghapus kolom
df.drop('new',axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [44]:
#tidak permanen penghapusannya
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [45]:
#penghapusan permanen
df.drop('new',axis=1,inplace=True)

df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [46]:
df.drop('E',axis=0) #hapus baris

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [47]:
#memilih baris berdasarkan label
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [48]:
df.iloc[2] #berdasarkan posisi

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [49]:
df.loc['B','Y']

-0.8480769834036315

In [ ]:
df.loc[['A','B'],['W','Y']]

##### berdasarkan syarat tertentu

In [60]:
df

A         B
Group Num                    
G1    1   -0.497104 -0.754070
      2   -0.943406  0.484752
      3   -0.116773  1.901755
G2    1    0.238127  1.996652
      2   -0.993263  0.196800
      3   -1.136645  0.000366

In [61]:
df>0

A      B
Group Num              
G1    1    False  False
      2    False   True
      3    False   True
G2    1     True   True
      2    False   True
      3    False   True

In [64]:
df[df>0]

A         B
Group Num                    
G1    1         NaN       NaN
      2         NaN  0.484752
      3         NaN  1.901755
G2    1    0.238127  1.996652
      2         NaN  0.196800
      3         NaN  0.000366

In [ ]:
df[df['W']>0]

In [ ]:
df[df['W']>0]['Y']

In [ ]:
df[df['W']>0][['Y','X']]

In [ ]:
df[(df['W']>0) & (df['Y'] > 1)]

###### detail mengenai indeks lainnya

In [ ]:
# Reset ke indeks default 0,1...n
df.reset_index()

In [ ]:
newind = 'CA NY WY OR CO'.split()

In [ ]:
df['States'] = newind

In [ ]:
df

In [ ]:
df.set_index('States')

In [ ]:
df

In [ ]:
df.set_index('States',inplace=True)

df

###### Hierarki Indeks

In [51]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [52]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1 -0.497104 -0.754070
   2 -0.943406  0.484752
   3 -0.116773  1.901755
G2 1  0.238127  1.996652
   2 -0.993263  0.196800
   3 -1.136645  0.000366

In [53]:
df.loc['G1']

A         B
1 -0.497104 -0.754070
2 -0.943406  0.484752
3 -0.116773  1.901755

In [54]:
df.loc['G1'].loc[1]

A   -0.497104
B   -0.754070
Name: 1, dtype: float64

In [55]:
df.index.names

FrozenList([None, None])

In [56]:
df.index.names = ['Group','Num']
df

A         B
Group Num                    
G1    1   -0.497104 -0.754070
      2   -0.943406  0.484752
      3   -0.116773  1.901755
G2    1    0.238127  1.996652
      2   -0.993263  0.196800
      3   -1.136645  0.000366

In [57]:
df.xs('G1')

A         B
Num                    
1   -0.497104 -0.754070
2   -0.943406  0.484752
3   -0.116773  1.901755

In [58]:
df.xs(['G1',1])

/var/folders/82/bw30xxnn03g3262lfz_rhq3m0000gn/T/ipykernel_13061/580597333.py:1: FutureWarning: Passing lists as key for xs is deprecated and will be removed in a future version. Pass key as a tuple instead.
  df.xs(['G1',1])


A   -0.497104
B   -0.754070
Name: (G1, 1), dtype: float64

In [59]:
df.xs(1,level='Num')

A         B
Group                    
G1    -0.497104 -0.754070
G2     0.238127  1.996652

### Mengatasi Data yang Hilang

In [ ]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [ ]:
df

In [ ]:
df.dropna()

In [ ]:
df.dropna(axis=1)

In [ ]:
df.dropna(thresh=2)

In [ ]:
df.fillna(value='FILL VALUE')

In [ ]:
df['A'].fillna(value=df['A'].mean())

### Merging, Joining, Concatenating

In [ ]:
#contoh DataFrame
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [ ]:
df1

In [ ]:
df2

In [ ]:
df3

#### Concatenating

In [ ]:
pd.concat([df1,df2,df3]) 

In [ ]:
pd.concat([df1,df2,df3],axis=1)

### ---------------------------------------------------------------------------------------------------------------------------------------------------------

In [ ]:
dfleft = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
dfright = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']}) 

In [ ]:
dfleft

In [ ]:
dfright

####  Merging

In [ ]:
pd.merge(dfleft,dfright,how='inner',on='key')

In [ ]:
dfleft = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
dfright = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
dfleft

In [ ]:
dfright

In [ ]:
pd.merge(dfleft, dfright, how='inner', on=['key1', 'key2'])

In [ ]:
pd.merge(dfleft, dfright, on=['key1', 'key2'])

In [ ]:
pd.merge(dfleft, dfright, how='outer', on=['key1', 'key2'])

In [ ]:
pd.merge(dfleft, dfright, how='right', on=['key1', 'key2'])

In [ ]:
pd.merge(dfleft, dfright, how='left', on=['key1', 'key2'])

#### Joining

In [ ]:
dfleft = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

dfright = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [ ]:
dfleft

In [ ]:
dfright

In [ ]:
dfleft.join(dfright)

In [ ]:
dfleft.join(dfright, how='outer')

### Operasi dalam Pandas

In [14]:
df = pd.DataFrame({'kolom1':[1,2,3,4],'kolom2':[444,555,666,444],'kolom3':['abc','def','ghi','xyz']})
df.head()

kolom1  kolom2 kolom3
0       1     444    abc
1       2     555    def
2       3     666    ghi
3       4     444    xyz

#### mendapatkan informasi nilai unik


In [15]:
df['kolom2'].unique()

array([444, 555, 666])

In [16]:
df['kolom2'].nunique()

3

In [17]:
df['kolom2'].value_counts()

444    2
555    1
666    1
Name: kolom2, dtype: int64

#### mengambil data tertentu


In [18]:
newdf = df[(df['kolom1']>2) & (df['kolom2']==444)]

In [19]:
newdf

kolom1  kolom2 kolom3
3       4     444    xyz

In [20]:
def times2(x):
    return x*2

In [ ]:
df['kolom1'].apply(times2)

In [ ]:
df['kolom3'].apply(len)

In [ ]:
df['kolom1'].sum()

In [21]:
del df['kolom1']

df

kolom2 kolom3
0     444    abc
1     555    def
2     666    ghi
3     444    xyz

In [22]:
df.columns

Index(['kolom2', 'kolom3'], dtype='object')

In [23]:
df.index

RangeIndex(start=0, stop=4, step=1)

#### Mengurutkan DataFrame

In [24]:
df

kolom2 kolom3
0     444    abc
1     555    def
2     666    ghi
3     444    xyz

In [ ]:
df.sort_values(by='kolom2')

#### Cek Nilai Null

In [26]:
df.isnull()

kolom2  kolom3
0   False   False
1   False   False
2   False   False
3   False   False

In [25]:
df.dropna()

kolom2 kolom3
0     444    abc
1     555    def
2     666    ghi
3     444    xyz

#### mengisi nilai NaN dengan nilai lain

In [27]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})

In [28]:
df.head() 

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [29]:
df.fillna('FILL')

col1   col2 col3
0   1.0   FILL  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3  FILL  444.0  xyz

In [30]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

In [31]:
df=pd.DataFrame(data)

In [32]:
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [33]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

### Input dan Output Data

#### CSV

#### CSV Input

In [ ]:
df = pd.read_csv('example')
df

#### CSV Output

In [ ]:
df.to_csv('example',index=False)

#### Excel

#### Excel Input

In [ ]:
pd.read_excel('Excel_Sample.xlsx', sheet_name='Sheet1')

#### Excel Output

In [ ]:
df.to_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

#### HTML

#### HTML Input

In [ ]:
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

In [ ]:
df = pd.read_html('example.html')

In [ ]:
df

In [ ]:
df[0]

#### HTML Output

In [ ]:
df[0].to_html('joblist.html')

#### SQL (Pilihan)


In [4]:
from sqlalchemy import create_engine

In [5]:
engine = create_engine('sqlite:///:memory:')

In [ ]:
df[0].to_sql('data', engine)

In [ ]:
sql_df = pd.read_sql('data',con=engine)

In [ ]:
sql_df

## Dataset


Import dataset yang sudah tersedia di sklearn


In [8]:
from sklearn import datasets

In [9]:
data = datasets.load_iris()

menunjukkan apa saja yang berada di dataset

In [10]:
print(data.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [11]:
print(data.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [12]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [ ]:
print(data.filename)

In [ ]:
print(data.filename)

In [ ]:
print(data.target)

In [ ]:
print(data.target_names)

In [ ]:
print(data.feature_names)

Daftar dataset utilites dari sklearn: 
 __[scikit-learn.org/stable/datasets.html](https://scikit-learn.org/stable/datasets.html)__

Beberapa sumber lainnya:

   1. __[www.kaggle.com/datasets](https://www.kaggle.com/datasets)__
   2. __[www.datasetsearch.research.google.com](https://www.datasetsearch.research.google.com)__
   3. __[archive.ics.uci.edu/ml/index.php](https://archive.ics.uci.edu/ml/index.php)__
   4. __[msropendata.com](https://www.msropendata.com)__